### ISSUE TITLE
Breaking after update

### ISSUE THREAD

**Issue by Pszek** [zalmoxisus/redux-devtools-extension#258]
system: OSX 10.11.6 
browser: Chrome 54.0.2840.98 (64-bit)
devtools: 2.10.1.1

stack trace: 
```
Uncaught TypeError: Cannot read property 'position' of undefined
    at DockMonitor.render (eval at <anonymous> (http://localhost:3500/app-bundle.js:5053:2), <anonymous>:131:32)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (eval at <anonymous> (http://localhost:3500/vendor-bundle.js:1027:2), <anonymous>:587:34)
    at ReactCompositeComponentWrapper._renderValidatedComponent (eval at <anonymous> (http://localhost:3500/vendor-bundle.js:1027:2), <anonymous>:607:32)
    at ReactCompositeComponentWrapper.wrapper [as _renderValidatedComponent] (eval at <anonymous> (http://localhost:3500/vendor-bundle.js:757:2), <anonymous>:66:21)
    at ReactCompositeComponentWrapper.mountComponent (eval at <anonymous> (http://localhost:3500/vendor-bundle.js:1027:2), <anonymous>:220:30)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (eval at <anonymous> (http://localhost:3500/vendor-bundle.js:757:2), <anonymous>:66:21)
    at Object.mountComponent (eval at <anonymous> (http://localhost:3500/vendor-bundle.js:949:2), <anonymous>:37:35)
    at ReactCompositeComponentWrapper.mountComponent (eval at <anonymous> (http://localhost:3500/vendor-bundle.js:1027:2), <anonymous>:225:34)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (eval at <anonymous> (http://localhost:3500/vendor-bundle.js:757:2), <anonymous>:66:21)
    at Object.mountComponent (eval at <anonymous> (http://localhost:3500/vendor-bundle.js:949:2), <anonymous>:37:35)
```

**Comment by zalmoxisus** [comment]
@Pszek thanks for the report. I see why it's happening and can revert removing the monitor state. But why do you need to render devtools components when using the extension? You shouldn't mix vanilla Redux DevTools with the extension.

**Comment by Pszek** [comment]
I don't mix explicite. I use sth like that:
```
const devTooling = window.devToolsExtension ? window.devToolsExtension() : DevTools.instrument()
```

**Comment by zalmoxisus** [comment]
@Pszek but somewhere you're still rendering `DevTools` component. You should prevent that as following:
```jsx
render(
  <Provider store={store}>
    <div>
      <TodoApp />
      { !window.devToolsExtension && <DevTools /> }
    </div>
  </Provider>
  document.getElementById('app')
);
```

**Comment by Pszek** [comment]
@zalmoxisus Thanks that solved it. Thank you for that great extension!

**Comment by zalmoxisus** [comment]
No problems. I'm still thinking whether we should include an empty monitor state as before to prevent those cases or let the component throws to let users know that they included them.

**Comment by Pszek** [comment]
Maybe leaving it like now, but adding helpful console log message (if possible) redirecing to page showing example code (as aforementioned)?
